name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Lint and Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm --filter server generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

