name: Deploy staging

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - apps/server/**
      - packages/**
      - infrastructure/**
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_server:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy-service.yml
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      aws_region: ${{ vars.AWS_REGION }}
      environment: staging
      service_name: server
      organization: teacherfox
