name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Welcome to Drip!\n\nBe sure to review our [pr guidelines](https://github.com/Dripshop/drip/blob/developer/.github/pr_guidelines)\n\nAnd our [commit guidelines](https://github.com/Dripshop/drip/blob/developer/.github/commit_guidelines)'
